<a href="https://colab.research.google.com/github/HoYoung528/2025-summer-mogakso/blob/main/AIML/note/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy ndarray 개요

In [ ]:
import numpy as np

In [ ]:
list1 = [1,2,3]
print("list1 type: ", type(list1))

array1 = np.array(list1)
print("array1 type: ", type(array1))
print("array1 shape: ", array1.shape)

array2 = np.array([[1,2,3],
                   [4,5,6]])
print("array2 type: ", type(array2))
print("array2 shape: ", array2.shape)

array3 = np.array([[1,2,3]])
print("array3 type: ", type(array3))
print("array3 shpae: ", array3.shape)

list1 type:  <class 'list'>
array1 type:  <class 'numpy.ndarray'>
array1 shape:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 shape:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 shpae:  (1, 3)


In [ ]:
print("array1: {:0}차원, array2: {:1}차원, array3:{:2}차원".format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


# ndarray 데이터 타입

In [ ]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))

print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

# 데이터 타입이 다르면 메모리가 큰 쪽으로 자동 형변환이 진행됨

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray 편리하게 생성하기 - arange, zeros, ones

In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# ndarray 차원과 크기 변경 - reshape

In [ ]:
array1 = np.arange(10)
print("array1: \n", array1)

array2 = array1.reshape(2, 5)
print("array2: \n", array2)

array3 = array1.reshape(5, 2)
print("array3: \n", array3)

array1: 
 [0 1 2 3 4 5 6 7 8 9]
array2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# 요소가 10개인데 4 x 3은 개수가 맞지 않으므로 에러 발생
array1.reshape(4, 3)

In [ ]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print("array2 shape: ", array2.shape)

array3 = array1.reshape(5, -1)
print("array3 shape: ", array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape:  (2, 5)
array3 shape:  (5, 2)


In [ ]:
# 요소가 10개인데 개수가 맞지 않으므로 에러 발생
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [ ]:
array1 = np.arange(8)

# 3차원 변환
array3d = array1.reshape((2,2,2))
print("array3d: \n", array3d)

# 3차원 -> 2차원 변환
array5 = array3d.reshape(-1, 1)
print("array5: \n", array5)
print("array5 shape: ", array5.shape)

# 1차원 -> 2차원 변환
array6 = array1.reshape(-1, 1)
print("array6: \n", array6)
print("array6 shape: ", array6.shape)

# 3차원 -> 1차원 변환
array1d = array3d.reshape(-1,)
print("array1d: ", array1d)
print("array1d shape: ", array1d.shape)

array3d: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array5: 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
array5 shape:  (8, 1)
array6: 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
array6 shape:  (8, 1)
array1d:  [0 1 2 3 4 5 6 7]
array1d shape:  (8,)


# ndarray 데이터 세트 선택

### 1. 단일 인덱싱

In [ ]:
array1 = np.arange(start=1, stop=10)
print("array1: ", array1)

value = array1[2]
print("value: ", value)
print(type(value))

array1:  [1 2 3 4 5 6 7 8 9]
value:  3
<class 'numpy.int64'>


In [ ]:
print("맨 뒤의 값: ", array1[-1], "뒤에서 두 번째 값: ", array1[-2])

맨 뒤의 값:  9 뒤에서 두 번째 값:  8


In [ ]:
array1[0] = 9
array1[8] = 0
print("array1: ", array1)

array1:  [9 2 3 4 5 6 7 8 0]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print("(row=1, col=1) index 가리키는 값", array2d[1][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=1, col=1) index 가리키는 값 5


### 2. 슬라이싱 인덱싱

In [ ]:
array1 = np.arange(start=1, stop=10)
print("array1: ", array1)
array3 = array1[0:3]
print("array3: ", array3)
print(type(array3))

array1:  [1 2 3 4 5 6 7 8 9]
array3:  [1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1 = np.arange(start=1, stop=10)

# 처음부터 2까지
array4 = array1[:3]
print(array4)

# 3부터 마지막까지
array5 = array1[3:]
print(array5)

# 전체 데이터
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print("array2d:\n", array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [ ]:
# n차원 배열에서 값을 고정하면 차원이 줄어들음 2차원 -> 1차원

print(array2d[0])
print(array2d[1])
print("array2d[0] shape: ", array2d[0].shape, "array2d[1] shape: ", array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape:  (3,) array2d[1] shape:  (3,)


### 3. 팬시 인덱싱

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print("array2d[[0, 1], 2]: \n", array3)

array4 = array2d[[0, 1], 0:2]
print("array2d[[0, 1], 0:2]: \n", array4)

array5 = array2d[[0, 1]]
print("array2d[[0, 1]]: \n", array5)

array2d[[0, 1], 2]: 
 [3 6]
array2d[[0, 1], 0:2]: 
 [[1 2]
 [4 5]]
array2d[[0, 1]]: 
 [[1 2 3]
 [4 5 6]]


### 4. 불린 인덱싱

In [ ]:
array1d = np.arange(start=1, stop=10)
print(array1d)

# array1d > 5 조건 적용
array3 = array1d[array1d > 5]
print("array1d > 5 인덱싱 결과 값: ", array3)

[1 2 3 4 5 6 7 8 9]
array1d > 5 인덱싱 결과 값:  [6 7 8 9]


In [ ]:
# 불린 인덱싱을 사용하지 않을 경우

arraay1d = np.arange(start=1, stop=10)
target = []

for i in range(9):
  if array1d[i] > 5:
    target.append(array1d[i])

array_selected = np.array(target)
print(array_selected)

[6 7 8 9]


# 행렬의 정렬 - sort()와 argsort()

### 1. sort()

In [ ]:
org_array = np.array([3, 1, 9, 5])
print("원본 배열: ", org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print("np.sort() 호출 후 반환된 정렬 배열: ", sort_array1)
print("np.sort() 호출 후 원본 배열: ", org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print("org_array.sort() 호출 후 반환된 배열: ", sort_array2)
print("org_array.sort() 호출 후 원본 배열: ", org_array)

원본 배열:  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 배열:  [1 3 5 9]
np.sort() 호출 후 원본 배열:  [3 1 9 5]
org_array.sort() 호출 후 반환된 배열:  None
org_array.sort() 호출 후 원본 배열:  [1 3 5 9]


In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print("내림차순으로 정렬: ", sort_array1_desc)

내림차순으로 정렬:  [9 5 3 1]


In [ ]:
array2d = np.array([[8, 12],
                    [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print("row 방향으로 정렬: \n", sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print("column 방향으로 정렬: \n", sort_array2d_axis1)

row 방향으로 정렬: 
 [[ 7  1]
 [ 8 12]]
column 방향으로 정렬: 
 [[ 8 12]
 [ 1  7]]


### argsort()

In [ ]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print("행렬 정렬 시 원본 배열의 인덱스: ", sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 배열의 인덱스:  [1 0 3 2]


In [ ]:
org_array = np.array([3, 1, 9, 5])[::-1]
sort_indices_desc = np.argsort(org_array)
print("행렬 내림차순 정렬 시 원본 배열의 인덱스: ", sort_indices_desc)

행렬 내림차순 정렬 시 원본 배열의 인덱스:  [2 3 0 1]


In [ ]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices = np.argsort(score_array)
print("성적 오름차순 정렬 시 score_array의 인덱스: ", sort_indices)
print("성적 오름차순 정렬 시 name_array의 이름 출력: ", name_array[sort_indices])

성적 오름차순 정렬 시 score_array의 인덱스:  [0 2 4 1 3]
성적 오름차순 정렬 시 name_array의 이름 출력:  ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# 선형대수 연산 - 행렬 내적과 전치 행렬

### 1. 행렬 내적

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_prodoct = np.dot(A, B)
print("행렬 내적 결과: \n", dot_prodoct)

행렬 내적 결과: 
 [[ 58  64]
 [139 154]]


### 2. 전치 행렬

In [ ]:
A = np.array([[1, 2],
             [3, 4]])
transpose_mat = np.transpose(A)
print("A의 전치 행렬: \n", transpose_mat)

A의 전치 행렬: 
 [[1 3]
 [2 4]]
